namespace SteveSharp.Generic;

// https://www.digminecraft.com/lists/enchantment_list_pc.php
internal static class EnchantmentHandler {
    internal static string Get(Enchantment enchantment) => enchantment switch {
        Enchantment.AquaAffinity => "minecraft:aqua_affinity",
        Enchantment.BaneOfArthropods => "minecraft:bane_of_arthropods",
        Enchantment.BlastProtection => "minecraft:blast_protection",
        Enchantment.Breach => "minecraft:breach",
        Enchantment.Channeling => "minecraft:channeling",
        Enchantment.CurseOfBinding => "minecraft:curse_of_binding",
        Enchantment.CurseOfVanishing => "minecraft:curse_of_vanishing",
        Enchantment.Density => "minecraft:density",
        Enchantment.DepthStrider => "minecraft:depth_strider",
        Enchantment.Efficiency => "minecraft:efficiency",
        Enchantment.FeatherFalling => "minecraft:feather_falling",
        Enchantment.FireAspect => "minecraft:fire_aspect",
        Enchantment.FireProtection => "minecraft:fire_protection",
        Enchantment.Flame => "minecraft:flame",
        Enchantment.Fortune => "minecraft:fortune",
        Enchantment.FrostWalker => "minecraft:frost_walker",
        Enchantment.Impaling => "minecraft:impaling",
        Enchantment.Infinity => "minecraft:infinity",
        Enchantment.Knockback => "minecraft:knockback",
        Enchantment.Looting => "minecraft:looting",
        Enchantment.Loyalty => "minecraft:loyalty",
        Enchantment.LuckOfTheSea => "minecraft:luck_of_the_sea",
        Enchantment.Lure => "minecraft:lure",
        Enchantment.Mending => "minecraft:mending",
        Enchantment.Multishot => "minecraft:multishot",
        Enchantment.Piercing => "minecraft:piercing",
        Enchantment.Power => "minecraft:power",
        Enchantment.ProjectileProtection => "minecraft:proyectile_protection",
        Enchantment.Protection => "minecraft:protection",
        Enchantment.Punch => "minecraft:punch",
        Enchantment.QuickCharge => "minecraft:quick_charge",
        Enchantment.Respiration => "minecraft:respiration",
        Enchantment.Riptide => "minecraft:riptide",
        Enchantment.Sharpness => "minecraft:sharpness",
        Enchantment.SilkTouck => "minecraft:silk_touch",
        Enchantment.Smite => "minecraft:smite",
        Enchantment.SoulSpeed => "minecraft:soul_speed",
        Enchantment.SweepingEdge => "minecraft:sweeping_edge",
        Enchantment.SwiftSneak => "minecraft:swift_sneak",
        Enchantment.Thorns => "minecraft:thorns",
        Enchantment.Unbreaking => "minecraft:unbreaking",
        Enchantment.WindBurst => "minecraft:wind_burst",
        _ => "Invalid input (enchantment not found)"
    };
}